# Generated by Django 5.1.3 on 2024-12-26 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('player_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('trophies', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sport_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('est_date', models.DateField()),
                ('email', models.EmailField(default='', max_length=254)),
                ('sport_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sport')),
            ],
        ),
    ]
